name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd hotel_campaign_automation
        pip install poetry
        poetry install
    - name: Run backend tests
      run: |
        cd hotel_campaign_automation
        poetry run pytest

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        cd hotel_campaign_automation/frontend
        npm ci
    - name: Run frontend tests
      run: |
        cd hotel_campaign_automation/frontend
        npm test

  model-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd hotel_campaign_automation
        pip install poetry
        poetry install
    - name: Run model tests
      run: |
        cd hotel_campaign_automation
        poetry run pytest test_backend.py
